### ISSUE TITLE
TagmeNED.java missing

### ISSUE THREAD

**Issue by silvanknecht** [WDAqua/Qanary-question-answering-components#1]
The component qanary_component-NED-tagme is missing source file TagmeNED.java

The asked file can be found in [TagmeNED.java](https://github.com/WDAqua/Frankenstein/blob/master/Qanary/qanary_component-NED-tagme/src/main/java/eu/wdaqua/qanary/tagme/TagmeNED.java)

I tried to build it and it is responding with error:
[buildErrorTagme.txt](https://github.com/WDAqua/Qanary-question-answering-components/files/2940588/buildErrorTagme.txt)

**Comment by aabccd021** [comment]
any progress on this?

**Comment by silvanknecht** [comment]
@aabccd021 
I didn't got an answer to this issue. However the Component is also used in [Frankenstein](https://github.com/WDAqua/Frankenstein/blob/master/Qanary/qanary_component-NED-tagme/src/main/java/eu/wdaqua/qanary/tagme/TagmeNED.java) . You can copy it from there. 
There are problems which you need to address tho.
1. The port could be already occupied and needs to be changed in the _applications.properties_ File.
2. Depending from where you start your Code you need to change the path from the _questions.txt_ File. In our Case we start everything from the target Folder so we had to adjust the code to:
`File f = new File("../src/main/resources/questions.txt");
//File f = new File("qanary_component-NED-tagme/src/main/resources/questions.txt");
`
3. If you use it with Qanary you also need to change up the parameters for the updateTripleStore Function:
`myQanaryUtils.updateTripleStore(sparql, myQanaryQuestion.getEndpoint().toString());
//myQanaryUtils.updateTripleStore(sparql);
`
cheers

**Comment by aabccd021** [comment]
@silvanknecht
Thank you in advance!

**Comment by anbo-de** [comment]
The issue was solved (c.f., https://github.com/WDAqua/Qanary-question-answering-components/tree/master/qanary_component-NED-tagme).
