### ISSUE TITLE
Python-QC-EAT-classifier: Move endpoint definition to config file

### ISSUE THREAD

**Issue by anbo-de** [WDAqua/Qanary-question-answering-components#103]
# DoD

 * [x] line https://github.com/WDAqua/Qanary-question-answering-components/blob/5f01380bbcde9071d564f21ec0884dafd7ad20d4/qanary_component-Python-QC-EAT-classifier/app/answer_type_classifier.py#L34 was changed, s.t., the service endpoint can be defined in the app.conf
 * [x] it was decided whether the method indexJson (https://github.com/Perevalov/Qanary-question-answering-components/blob/275ccc8742a8caddc98d5fff2e9c243f202328b8/qanary_component-Python-QC-EAT-classifier/app/answer_type_classifier.py#L75) is required or not

**Comment by Perevalov** [comment]
@anbo-de Please, check if DoD is completed. The changes were done within this [commit](https://github.com/WDAqua/Qanary-question-answering-components/commit/0fc2fe64077fbda4dbb2566384c3c92f8d76a582) and #104

**Comment by anbo-de** [comment]
Well done.
