### ISSUE TITLE
QB-Sina is missing a required .jar file

### ISSUE THREAD

**Issue by jannlemm0913** [WDAqua/Qanary-question-answering-components#2]
In SINA.java:138, there is a process using qanary_component-QB-Sina/src/main/resources/sina-0.0.1.jar, but that file is not in the folder. 

I found a sina-0.0.1.jar file [here](https://github.com/WDAqua/Pipeline/tree/master/libs/wdaqua/sina/0.0.1) , but there seems to be two URIs hardcoded into the query building process. So I can't use it with my own arguments, atleast I have not succeeded in doing so.

**Comment by kulsingh** [comment]
Do you need the code or you need to use SINA? If you have to use SINA or another component, http://frankenstein.qanary-qa.com can be used. If you need access to the code, ping me your email ID, I can pass you the latest code in bitbucket which we haven't made public.

**Comment by jannlemm0913** [comment]
I need to be able to run the qanary component SINA (qanary_component-QB-Sina-1.0.0.jar). I am currently working with @silvanknecht on our bachelor thesis and we want to evaluate different pipeline combinations with the english questions from QALD 9. 
I will send you my email ID and would be very thankful for further help, as other components also give us issues.

**Comment by jannlemm0913** [comment]
Any ETA on your answer @kulsingh ?

**Comment by aabccd021** [comment]
any progress?

**Comment by jannlemm0913** [comment]
Yes, @kulsingh and I talked over Skype and I got temporary access to their bitbucket repository. Since then we have used SINA in our systems without much trouble. Maybe he can help you in the same way if you need to run the component.

**Comment by kulsingh** [comment]
Pls drop me an email on kskuldeepvit at gmail DOT com, I will help you to get the bit bucket access.

**Comment by aabccd021** [comment]
@kulsingh
I dropped my email on kskuldeepvit at gmail DOT com. Thank you for your help.
