### ISSUE TITLE
No versions available for eu.wdaqua.qanary

### ISSUE THREAD

**Issue by joraojr** [WDAqua/Qanary-question-answering-components#8]
Hi,

 I'm trying to build all components of the qanary using the docker but only the profile `tinytutorial` of the pom.xml is working. When I try to build all of the components, I receive the following error:

> Failed to collect dependencies at eu.wdaqua.qanary:qa.component:jar:[1.,2.): No versions available for eu.wdaqua.qanary:qa.component:jar:[1.,2.) within specified range -> [Help 1]

I switched the range to [2.0.0,3.0.0) as it is in the pom.xml of the new NED-DBpediaSpotlight, but still now working. Is the version `qa.component:jar:[1.,2.)` no longer available?

**Comment by anbo-de** [comment]
Yes, sorry for these circumstances. We are currently in the transformation to a new Qanary version. Which will still take some time. 

However, the older versions are still available. You might check out https://github.com/WDAqua/Qanary/commit/9b294281b48cedcf8f9c0460b81313b81be8bf08 or an older version which includes the Qanary component in version 1.x.x.

Hope it helps.

**Comment by joraojr** [comment]
Thanks @anbo-de !!
